server:
  port: 7003
spring:
  application:
     name: gateway-zuul
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eureka
  #instance:
    #ip-address: true
zuul:
  ignoredServices: '*'
  routes:
    #provider:
      #path: /provider/**
      #stripPrefix: true
      #url: http://localhost:7001/provider
    #eureka-provider: /provider/**
    provider-service:
      path: /api/**
      #stripPrefix: false
      serviceId: eureka-provider